services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 -js"
    networks:
      - localnet

  nats-1:
    image: nats
    container_name: nats-1
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js"
    depends_on:
      - nats
    networks:
      - localnet

  nats-2:
    image: nats
    container_name: nats-2
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js"
    depends_on:
      - nats
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
